name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-14-arm64
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '6.0.0'  # Make sure to quote the version to avoid YAML interpreting it as a float
    
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v
